name: Build

on:
    schedule:
        - cron: '00 15 * * *'
    workflow_dispatch:

env:
    PYTHON_VER: "3.12.2"
    POETRY_VER: "1.7.1"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: "Setup Python, Poetry and Dependencies"
              uses: packetcoders/action-setup-cache-python-poetry@v1.1.0
              with:
                python-version: ${{ env.PYTHON_VER }}
                poetry-version: ${{ env.POETRY_VER }}
            - name: Build
              run: |
                poetry run python scripts/bundle.py
            - name: "Commit & Push"
              uses: EndBug/add-and-commit@v9
              with:
                add: 'www'
                default_author: github_actions
                message: "task(html): build static html"
            - name: "Send Notification on Fail"
              if: failure()
              uses: sarisia/actions-status-discord@v1
              with:
                webhook: ${{ secrets.DISCORD_WEBHOOK }}
                status: ${{ job.status }}
                title: "web build"
                description: "build static html files"
                username: "GitHub :>"
                url: "https://github.com/MurkyYT/cs-auto"
                nofail: true
