name: Build

on:
    schedule:
        - cron: '00 15 * * *'
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v7
            - name: "Setup UV"
              uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4 # v10.1.0
              with:
                resolution-strategy: "highest"
                restore-cache: "true"
            - name: Sync dependencies
              shell: bash
              run: uv sync
            - name: Build
              env:
                GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
              run: |
                uv run scripts/bundle.py
            - name: "Commit uv.lock"
              uses: EndBug/add-and-commit@v11.1.1
              with:
                add: 'uv.lock'
                default_author: github_actions
                message: "task(deps): update uv.lock"
                push: false
            - name: "Commit www & Push"
              uses: EndBug/add-and-commit@v11.1.1
              with:
                add: 'www'
                default_author: github_actions
                message: "task(html): build static html"
                push: true
            - name: "Send Notification on Fail"
              if: failure()
              uses: sarisia/actions-status-discord@v1
              with:
                webhook: ${{ secrets.DISCORD_WEBHOOK }}
                status: ${{ job.status }}
                title: "web build"
                description: "build static html files"
                username: "GitHub"
                url: "https://github.com/MurkyYT/cs-auto"
                nofail: true
